[aws]
disabled=true

[package]
symbol="  "
style="bold red"

[lua]
symbol="󰢱 "
style="bold blue"

[python]
symbol="  "
style="bold yellow"

[character]
success_symbol='[.₊⊹ 󱞩 ](bold purple)'
error_symbol='[.₊⊹ 󱞩 ](bold blue)'
